name: phasing-snakemake
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python
  - bioconda::bcftools
  - shapeit4
  - bcftools
  - whatshap
  - hapcut2
  - pip
  - pip:
    - snakemake
    - snakemake-executor-plugin-slurm
    - pandas
    - pysam