name: phasing-snakemake
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::bcftools
  - bioconda::snakemake-executor-plugin-slurm
  - pandas
  - shapeit5
  - bcftools